### ISSUE TITLE
Android support library update

### ISSUE THREAD

**Issue by iamtheib** [saurabharora90/InfiniteRecyclerView#5]
For some reason that escapes me, I get ther following error on intial load of the recycler view.

```
java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionViewHolder{78e4fb0 position=8 id=-1, oldPos=6, pLpos:6 scrap [attachedScrap] tmpDetached no parent}
    at android.support.v7.widget.RecyclerView$Recycler.validateViewHolderForOffsetPosition(RecyclerView.java:4505)
    at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4636)
    at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4617)
    at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:1994)
    at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1390)
    at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1353)
    at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:574)
    at android.support.v7.widget.RecyclerView.dispatchLayoutStep1(RecyclerView.java:2979)
    at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:2904)
    at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3283)
    at android.view.View.layout(View.java:16636)
    at android.view.ViewGroup.layout(ViewGroup.java:5437)
    at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1079)
    at android.view.View.layout(View.java:16636)
    at android.view.ViewGroup.layout(ViewGroup.java:5437)
    at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
    at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
    at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
    at android.view.View.layout(View.java:16636)
    at android.view.ViewGroup.layout(ViewGroup.java:5437)
    at android.support.v4.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:596)
    at android.view.View.layout(View.java:16636)
    at android.view.ViewGroup.layout(ViewGroup.java:5437)
    at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1695)
    at android.view.View.layout(View.java:16636)
    at android.view.ViewGroup.layout(ViewGroup.java:5437)
    at android.support.design.widget.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:122)
    at android.support.design.widget.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:42)
    at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:1192)
    at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:814)
    at android.view.View.layout(View.java:16636)
    at android.view.ViewGroup.layout(ViewGroup.java:5437)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
    at android.view.View.layout(View.java:16636)
    at android.view.ViewGroup.layout(ViewGroup.java:5437)
    ...
```

According to this [SO thread](http://stackoverflow.com/questions/31759171/recyclerview-and-java-lang-indexoutofboundsexception-inconsistency-detected-in), the issue is in `v23.1.1` of the support library, which is currently being used by this library. Would you consider upgrading the version of the support library being used.

**Comment by jk2pr** [comment]
java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid item position 49(offset:49).state:50
                                                                              at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4957)
                                                                              at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4913)
                                                                              at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2029)
                                                                              at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1414)
                                                                              at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1377)
                                                                              at android.support.v7.widget.LinearLayoutManager.scrollBy(LinearLayoutManager.java:1193)
                                                                              at android.support.v7.widget.LinearLayoutManager.scrollVerticallyBy(LinearLayoutManager.java:1043)
                                                                              at android.support.v7.widget.RecyclerView.scrollByInternal(RecyclerView.java:1552)
                                                                              at android.support.v7.widget.RecyclerView.onTouchEvent(RecyclerView.java:2649)
                                                                              at android.view.View.dispatchTouchEvent(View.java:8471)
                                                                              at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2399)
                                                                              at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2092)
                                                                              at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
                                                                              at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
                                                                              at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
                                                                              at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
                                                                              at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
                                                                              at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
                                                                              at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
                                                                              at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
                                                                              at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
                                                                              at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
                                                                              at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
                                                                              at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
                                                                              at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
                                                                              at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
                                                                              at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
                                                                              at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
                                                                              at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2369)
                                                                              at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1719)
                                                                              at android.app.Activity.dispatchTouchEvent(Activity.java:2742)
                                                                              at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:63)
                                                                              at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:63)
                                                                              at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2330)
                                                                              at android.view.View.dispatchPointerEvent(View.java:8666)
                                                                              at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4123)
                                                                              at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:3989)
                                                                              at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3544)
                                                                              at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3597)
                                                                              at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3563)
                                                                              at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3680)
                                                                              at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3571)
                                                                              at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3737)
                                                                              at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3544)
                                                                              at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3597)
                                                                              at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3563)
                                                                              at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3571)
                                                                              at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3544)
                                                                              at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5807)
                                                                          	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl

**Comment by saurabharora90** [comment]
I don't think it is a support library issue. Can you post an example of how you are using it?

**Comment by jk2pr** [comment]
// call moredataloaded on Recyclerview
// increase count for next hit on server
//  add data loaded from server to existing dataset

```
                          mData.addAll(mNotificationObject.getNotifyList());
                              recyclerView.moreDataLoaded();

                                        _count += 1;
                                    
                               

```

**Comment by saurabharora90** [comment]
Okay. One more thing: I hope this update is not being done on a background thread?

**Comment by jk2pr** [comment]
Yes, I am not doing it in background thread, but still getting

>  java.lang.IndexOutOfBoundsException: Inconsistency detected

**Comment by saurabharora90** [comment]
Try with the latest version? I updated the support library

**Comment by iamtheib** [comment]
@jk2pr Are you still seeing this issue? Or can this be closed?

**Comment by iamtheib** [comment]
The support libraries have been updated to `v23.4.0`.
